"""API client — configured automatically by the knot runtime."""
from typing import Any
def get(path: str) -> dict[str, Any]: ...
def post(path: str, body: dict[str, Any] | None = ..., expect: int = ...) -> dict[str, Any]: ...
def put(path: str, body: dict[str, Any] | None = ..., expect: int = ...) -> dict[str, Any]: ...
def delete(path: str, expect: int = ...) -> dict[str, Any]: ...
