"""Knot event functions.

Space-side: emit() raises custom events from inside a space.
Server-side (sink scripts): get_*() accessors and metadata functions.
"""
from typing import Any

# Space-side: emit a custom event (available in any in-space script)
def emit(type: str, payload: dict[str, Any] | None = ...) -> bool: ...

# Server-side: payload accessors (available in sink scripts only)
def get_string(name: str, default: str = "") -> str: ...
def get_int(name: str, default: int = 0) -> int: ...
def get_bool(name: str, default: bool = False) -> bool: ...
def get_list(name: str, default: list[Any] | None = None) -> list[Any]: ...
def get_dict(name: str, default: dict[str, Any] | None = None) -> dict[str, Any]: ...

# Server-side: metadata functions (available in sink scripts only)
def type() -> str: ...
def id() -> str: ...
def ts() -> str: ...
def space() -> dict[str, Any]: ...
def space_urls() -> dict[str, str]: ...
def actor() -> dict[str, Any]: ...
def custom() -> dict[str, str]: ...
