"""Knot event functions.

Space-side: emit() raises custom events from inside a space.
Server-side (sink scripts): get_*() accessors and metadata functions.
"""
from typing import Any

# Space-side: emit a custom event (available in any in-space script)
def emit(type: str, payload: dict[str, Any] | None = ...) -> bool: ...
    """Emit a custom event from this space. The 'custom.' prefix is added automatically."""

# Server-side: payload accessors (available in sink scripts only)
def get_string(name: str, default: str = "") -> str: ...
    """Get a payload parameter as string (sink scripts only)"""
def get_int(name: str, default: int = 0) -> int: ...
    """Get a payload parameter as integer (sink scripts only)"""
def get_bool(name: str, default: bool = False) -> bool: ...
    """Get a payload parameter as boolean (sink scripts only)"""
def get_list(name: str, default: list[Any] | None = None) -> list[Any]: ...
    """Get a payload parameter as list (sink scripts only)"""
def get_dict(name: str, default: dict[str, Any] | None = None) -> dict[str, Any]: ...
    """Get a payload parameter as dict (sink scripts only)"""

# Server-side: metadata functions (available in sink scripts only)
def type() -> str: ...
    """Get the event type string (sink scripts only)"""
def id() -> str: ...
    """Get the event UUIDv7 id (sink scripts only)"""
def ts() -> str: ...
    """Get the event HLC timestamp string (sink scripts only)"""
def space() -> dict[str, Any]: ...
    """Get the source space dict (sink scripts only)"""
def space_urls() -> dict[str, str]: ...
def actor() -> dict[str, Any]: ...
    """Get the actor dict with id, username, kind (sink scripts only)"""
def custom() -> dict[str, str]: ...
    """Get custom fields dict (sink scripts only)"""
