"""Store, read and copy files in buckets replicated across the cluster, and manage the buckets."""
import builtins
from typing import Any
def list_buckets(all: bool = ...) -> builtins.list[dict[str, Any]]:
    """List the buckets you own or that are shared with you; all=True lists every bucket (file storage managers). Each has name (<owner>--<name>), display_name, owner, owner_id, access (owner, write or read), size, count, shared (type, name and access of each share) and created_at"""
    ...
def get_bucket(name: str) -> dict[str, Any]:
    """Get one bucket by its short name (your own) or full name; same fields as list_buckets"""
    ...
def create_bucket(name: str) -> dict[str, Any]:
    """Create a bucket named <your username>--<name>; name is 3 to 30 lowercase letters, digits and hyphens with no --"""
    ...
def delete_bucket(name: str, force: bool = ...) -> bool:
    """Delete a bucket; a bucket that holds files is refused unless force=True, which deletes them with it"""
    ...
def share_bucket(name: str, user: str | None = ..., group: str | None = ..., everyone: bool = ..., access: str = ...) -> dict[str, Any]:
    """Share a bucket with exactly one of a user (username or email), a group or everyone; access is "read" (default) or "write". Sharing again changes the access"""
    ...
def unshare_bucket(name: str, user: str | None = ..., group: str | None = ..., everyone: bool = ...) -> dict[str, Any]:
    """Stop sharing a bucket with exactly one of a user, a group or everyone"""
    ...
def transfer_bucket(name: str, user: str, force: bool = ...) -> dict[str, Any]:
    """Give a bucket to another user, who must be allowed to own buckets; it is renamed into their namespace and their quota is charged. force allows going over their quota (file storage managers only)"""
    ...
def usage() -> dict[str, Any]:
    """Your file storage usage and limits: used_bytes, files, buckets, quota_bytes and max_buckets (0 for no limit)"""
    ...
def list_files(bucket: str, prefix: str = ..., recursive: bool = ...) -> dict[str, Any]:
    """List the files in a bucket. Returns files (key, size, etag, sha256, content_type, modified_at) and folders (prefixes ending in /). prefix restricts to keys starting with it, so end it with / for a folder; recursive=True lists every file below the prefix and returns no folders"""
    ...
def read_file(bucket: str, key: str) -> bytes:
    """Read a file's content as bytes (at most 64 MB in a script)"""
    ...
def read_text(bucket: str, key: str) -> str:
    """Read a file's content as UTF-8 text"""
    ...
def write_file(bucket: str, key: str, data: str | bytes, content_type: str = ...) -> dict[str, Any]:
    """Write a file, replacing any file with that key; folders need no creating. data is a string (written as UTF-8) or bytes, at most 64 MB at a time. content_type defaults to text/plain for a string, else application/octet-stream. Returns the file's key, size, etag, sha256, content_type and modified_at"""
    ...
def delete_file(bucket: str, key: str) -> bool:
    """Delete a file"""
    ...
def copy_file(source_bucket: str, source_key: str, dest_bucket: str, dest_key: str) -> dict[str, Any]:
    """Copy a file within a bucket or to another, on the server without transferring its content; keeps its content type, metadata and modification time and replaces any file at the destination"""
    ...
def file_exists(bucket: str, key: str) -> bool:
    """Check whether there is a file with exactly this key"""
    ...
