"""Manage groups."""
from typing import Any
def list() -> list[dict[str, Any]]: ...
def get(group_id: str) -> dict[str, Any]: ...
def create(name: str, max_spaces: int = ..., compute_units: int = ..., storage_units: int = ..., max_tunnels: int = ...) -> str: ...
def update(group_id: str, name: str | None = ..., max_spaces: int | None = ..., compute_units: int | None = ..., storage_units: int | None = ...) -> bool: ...
def delete(group_id: str) -> bool: ...
