"""Space health check functions.

Only available in agent-side health check scripts and `knot run-script`.
"""
from typing import Any

def http_head(url: str, skip_ssl_verify: bool = ..., timeout: int = ...) -> bool: ...
def tcp_port(port: int, timeout: int = ...) -> bool: ...
def program(command: str, timeout: int = ...) -> bool: ...
def check_result(healthy: bool) -> Any: ...
