"""Manage the scheduled jobs of a space.

Job definitions are stored on the space and pushed to its agent, so they
survive restarts and can be changed while the space is stopped.
"""

from typing import Any

def list(space: str) -> dict[str, Any]: ...
    """List a space's job definitions and runner state. Works while the space is stopped."""
def run(space: str, name: str) -> bool: ...
    """Trigger a job immediately by name. Works for disabled and manual-only jobs; the space must be running."""
def add(space: str, name: str, command: str, schedule: str = ..., enabled: bool = ...) -> bool: ...
    """Add a job to a space. Schedule is a 5-field cron expression, e.g. "0 2 * * *"; empty for a manual-only job."""
def update(space: str, name: str, command: str | None = ..., schedule: str | None = ..., enabled: bool | None = ...) -> bool: ...
    """Update a job's command, schedule or enabled state; only given arguments change. Pass schedule='' for manual-only."""
def remove(space: str, name: str) -> bool: ...
    """Remove a job from a space."""
def enable(space: str, name: str) -> bool: ...
    """Enable a job so it fires automatically."""
def disable(space: str, name: str) -> bool: ...
    """Disable a job so it does not fire automatically. Manual runs still work."""
def enable_runner(space: str) -> bool: ...
    """Start the space's job runner: scheduled jobs fire."""
def disable_runner(space: str) -> bool: ...
    """Stop the space's job runner. Manual runs still work."""
