"""Manage the scheduled jobs of a space.

Job definitions are stored on the space and pushed to its agent, so they
survive restarts and can be changed while the space is stopped.
"""

from typing import Any

def list(space: str) -> dict[str, Any]: ...
def run(space: str, name: str) -> bool: ...
def add(space: str, name: str, command: str, schedule: str = ..., enabled: bool = ...) -> bool: ...
def update(space: str, name: str, command: str | None = ..., schedule: str | None = ..., enabled: bool | None = ...) -> bool: ...
def remove(space: str, name: str) -> bool: ...
def enable(space: str, name: str) -> bool: ...
def disable(space: str, name: str) -> bool: ...
def enable_runner(space: str) -> bool: ...
def disable_runner(space: str) -> bool: ...
