"""MCP tool discovery and execution."""
from typing import Any
def list_tools() -> list[dict[str, Any]]: ...
    """Get list of available MCP tools and their parameters"""
def call_tool(name: str, arguments: dict[str, Any]) -> Any: ...
    """Call an MCP tool directly. Arguments should be a dict"""
def tool_search(query: str, max_results: int = ...) -> list[dict[str, Any]]: ...
    """Search for tools by keyword. Returns list of matching tools"""
def execute_tool(name: str, arguments: dict[str, Any]) -> Any: ...
    """Execute a discovered tool. Use full name for namespaced tools"""
