"""MCP tool discovery and execution."""
from typing import Any
def list_tools() -> list[dict[str, Any]]: ...
def call_tool(name: str, arguments: dict[str, Any]) -> Any: ...
def tool_search(query: str, max_results: int = ...) -> list[dict[str, Any]]: ...
def execute_tool(name: str, arguments: dict[str, Any]) -> Any: ...
