"""Manage space pools — fixed-size, self-healing groups of identical spaces."""

from typing import Any

def list() -> list[dict[str, Any]]: ...
def get(name: str) -> dict[str, Any]: ...
def create(name: str, template_name: str, startup_script_id: str = ..., desired_count: int = ..., active: bool = ...) -> str: ...
def update(name: str, desired_count: int | None = ..., active: bool | None = ...) -> bool: ...
def delete(name: str) -> bool: ...
def set_size(name: str, desired_count: int) -> bool: ...
def start(name: str) -> bool: ...
def stop(name: str) -> bool: ...
