"""Manage roles."""
from typing import Any
def list() -> list[dict[str, Any]]: ...
    """List all roles"""
def get(role_id: str) -> dict[str, Any]: ...
    """Get role by ID (UUID only)"""
def create(name: str, permissions: list[int] | None = ...) -> str: ...
    """Create a new role"""
def update(role_id: str, name: str | None = ..., permissions: list[int] | None = ...) -> bool: ...
    """Update role properties"""
def delete(role_id: str) -> bool: ...
    """Delete a role by UUID"""
