"""Manage roles."""
from typing import Any
def list() -> list[dict[str, Any]]: ...
def get(role_id: str) -> dict[str, Any]: ...
def create(name: str, permissions: list[int] | None = ...) -> str: ...
def update(role_id: str, name: str | None = ..., permissions: list[int] | None = ...) -> bool: ...
def delete(role_id: str) -> bool: ...
