"""Manage and execute scripts."""
from typing import Any
def list(owner: str | None = ..., all_zones: bool = ..., include_inactive: bool = ..., script_type: str | None = ...) -> list[dict[str, Any]]: ...
    """List scripts visible to the current user. Defaults to active scripts in the current zone; use script_type='script' to filter to runnable scripts (exclude MCP tool definitions)."""
def list_global(all_zones: bool = ...) -> list[dict[str, Any]]: ...
    """List global scripts available for template editing"""
def get(script_id: str) -> dict[str, Any]: ...
    """Get script details by UUID"""
def get_by_name(name: str) -> dict[str, Any]: ...
    """Get script details by name, respecting user script shadowing"""
def get_content(name: str, script_type: str = ...) -> str: ...
    """Get script content by name and type"""
def create(name: str, content: str, description: str = ..., owner: str | None = ..., groups: list[str] | None = ..., zones: list[str] | None = ..., **kwargs: Any) -> str: ...
    """Create a script. Use owner='current' for an own script."""
def update(script_id: str, name: str | None = ..., content: str | None = ..., description: str | None = ..., groups: list[str] | None = ..., **kwargs: Any) -> bool: ...
    """Update a script while preserving fields not passed"""
def delete(script_id: str) -> bool: ...
    """Delete a script by UUID"""
def execute(space_name: str, script_name: str | None = ..., script_id: str | None = ..., content: str | None = ..., args: list[str] | None = ...) -> dict[str, Any]: ...
    """Execute a named, ID-based, or inline script in a running space"""
def execute_content(space_name: str, content: str, args: list[str] | None = ...) -> dict[str, Any]: ...
    """Execute inline script content in a running space"""
