"""Manage and execute scripts."""
from typing import Any
def list(owner: str | None = ..., all_zones: bool = ..., include_inactive: bool = ..., script_type: str | None = ...) -> list[dict[str, Any]]: ...
def list_global(all_zones: bool = ...) -> list[dict[str, Any]]: ...
def get(script_id: str) -> dict[str, Any]: ...
def get_by_name(name: str) -> dict[str, Any]: ...
def get_content(name: str, script_type: str = ...) -> str: ...
def create(name: str, content: str, description: str = ..., owner: str | None = ..., groups: list[str] | None = ..., zones: list[str] | None = ..., **kwargs: Any) -> str: ...
def update(script_id: str, name: str | None = ..., content: str | None = ..., description: str | None = ..., groups: list[str] | None = ..., **kwargs: Any) -> bool: ...
def delete(script_id: str) -> bool: ...
def execute(space_name: str, script_name: str | None = ..., script_id: str | None = ..., content: str | None = ..., args: list[str] | None = ...) -> dict[str, Any]: ...
def execute_content(space_name: str, content: str, args: list[str] | None = ...) -> dict[str, Any]: ...
