"""Manage skills."""
from typing import Any
def list(owner: str | None = ...) -> list[dict[str, Any]]: ...
def get(name_or_id: str) -> dict[str, Any]: ...
def create(content: str, is_global: bool = ..., groups: list[str] | None = ..., zones: list[str] | None = ...) -> str: ...
def update(name_or_id: str, content: str | None = ..., groups: list[str] | None = ..., zones: list[str] | None = ...) -> bool: ...
def delete(name_or_id: str) -> bool: ...
def search(query: str) -> list[dict[str, Any]]: ...
