"""Manage slash commands."""
from typing import Any

def list(owner: str | None = ..., all_zones: bool = ...) -> list[dict[str, Any]]: ...
def get(name_or_id: str) -> dict[str, Any]: ...
def create(content: str, is_global: bool = ..., groups: list[str] | None = ..., zones: list[str] | None = ..., active: bool = ...) -> str: ...
def update(name_or_id: str, content: str | None = ..., groups: list[str] | None = ..., zones: list[str] | None = ..., active: bool | None = ...) -> bool: ...
def delete(name_or_id: str) -> bool: ...
