"""Manage development spaces."""

from typing import Any, Optional

def list(all_zones: bool = ...) -> list[dict[str, Any]]: ...
def get(name: str) -> dict[str, Any]: ...
def create(
    name: str,
    template_name: str,
    description: str = ...,
    shell: str = ...,
    depends_on: list[str] | None = ...,
    icon_url: str = ...,
    custom_fields: list[dict[str, str]] | None = ...,
    start_on_create: bool = ...,
) -> str: ...
def update(
    name: str,
    new_name: str | None = ...,
    description: str | None = ...,
    shell: str | None = ...,
    template_name: str | None = ...,
    icon_url: str | None = ...,
    custom_fields: list[dict[str, str]] | None = ...,
    start: bool = ...,
    stop: bool = ...,
    restart: bool = ...,
) -> bool: ...
def delete(name: str) -> bool: ...
def start(name: str) -> bool: ...
def stop(name: str) -> bool: ...
def restart(name: str) -> bool: ...
def is_running(name: str) -> bool: ...
def usage_current(name: str) -> dict[str, Any]: ...
def usage_history(name: str, range: str = ...) -> list[dict[str, Any]]: ...
def set_description(name: str, description: str) -> bool: ...
def get_description(name: str) -> str: ...
def get_dependencies(name: str) -> list[str]: ...
def set_dependencies(name: str, depends_on: list[str]) -> bool: ...
def get_stack(name: str) -> str: ...
def set_stack(name: str, stack: str) -> bool: ...
def get_field(name: str, field: str) -> str: ...
def set_field(name: str, field: str, value: str) -> bool: ...
def transfer(name: str, user_id: str) -> bool: ...
def share(name: str, user_ids: list[str]) -> bool: ...
def unshare(name: str, user_id: str | None = ...) -> bool: ...
def run(name: str, command: str, args: list[str] | None = ..., timeout: int = ..., workdir: str = ...) -> dict[str, Any]: ...
def run_script(name: str, script_name: str, args: list[str] | None = ...) -> dict[str, Any]: ...
def eval(name: str, code: str, args: list[str] | None = ...) -> dict[str, Any]: ...
def read_file(name: str, file_path: str, offset: int = ..., limit: int = ...) -> str: ...
def write_file(name: str, file_path: str, content: str, mode: str = ...) -> bool: ...
def grep(
    name: str,
    pattern: str,
    path: str,
    literal: bool = ...,
    recursive: bool = ...,
    ignore_case: bool = ...,
    glob: str = ...,
    follow_links: bool = ...,
    max_size: int = ...,
    workdir: str = ...,
) -> list[dict[str, Any]]: ...
def find(
    name: str,
    path: str = ...,
    recursive: bool = ...,
    type: str = ...,
    name_glob: str = ...,
    mtime_min: float | None = ...,
    mtime_max: float | None = ...,
    size_min: int | None = ...,
    size_max: int | None = ...,
    include_hidden: bool = ...,
    follow_links: bool = ...,
    max_depth: int = ...,
    workdir: str = ...,
) -> list[str]: ...
def sed_replace(
    name: str,
    old: str,
    new: str,
    path: str,
    recursive: bool = ...,
    ignore_case: bool = ...,
    glob: str = ...,
    follow_links: bool = ...,
    max_size: int = ...,
    workdir: str = ...,
) -> int: ...
def sed_replace_pattern(
    name: str,
    pattern: str,
    new: str,
    path: str,
    recursive: bool = ...,
    ignore_case: bool = ...,
    glob: str = ...,
    follow_links: bool = ...,
    max_size: int = ...,
    workdir: str = ...,
) -> int: ...
def sed_extract(
    name: str,
    pattern: str,
    path: str,
    recursive: bool = ...,
    ignore_case: bool = ...,
    glob: str = ...,
    follow_links: bool = ...,
    max_size: int = ...,
    workdir: str = ...,
) -> list[dict[str, Any]]: ...
def edit_file(
    name: str,
    file_path: str,
    search: str,
    replace: str,
    workdir: str = ...,
) -> int: ...
def port_forward(source_space: str, local_port: int, remote_space: str, remote_port: int, persistent: bool = ..., force: bool = ...) -> bool: ...
def port_list(name: str) -> list[dict[str, Any]]: ...
def port_stop(name: str, local_port: int) -> bool: ...
def port_apply(source_space: str, forwards: list[dict[str, Any]]) -> bool: ...
def tunnel_start(space: str, protocol: str, port: int, name: str) -> str: ...
def tunnel_list(space: str) -> list[dict[str, Any]]: ...
def tunnel_stop(space: str, name: str) -> bool: ...
