"""Manage stacks and stack definitions."""
from typing import Any
def list_defs() -> list[dict[str, Any]]: ...
def get_def(name: str) -> dict[str, Any]: ...
def create_def(name: str, description: str = ..., icon_url: str = ..., scope: str = ..., active: bool = ..., groups: list[str] | None = ..., zones: list[str] | None = ..., spaces: list[dict[str, Any]] | None = ...) -> str: ...
def update_def(name: str, **fields: Any) -> bool: ...
def delete_def(name: str) -> bool: ...
def validate_def(spaces: list[dict[str, Any]], name: str = ..., description: str = ..., icon_url: str = ..., scope: str = ..., active: bool = ..., groups: list[str] | None = ..., zones: list[str] | None = ...) -> dict[str, Any]: ...
def add_component(stack_definition: dict[str, Any], template: str, name: str, description: str = ..., shell: str = ..., **kwargs: Any) -> dict[str, Any]: ...
def remove_component(stack_definition: dict[str, Any], name: str) -> dict[str, Any]: ...
def create(definition_name: str, prefix: str, stack_name: str | None = ...) -> list[str]: ...
def delete(stack_name: str) -> bool: ...
def start(stack_name: str) -> bool: ...
def stop(stack_name: str) -> bool: ...
def restart(stack_name: str) -> bool: ...
def list() -> list[dict[str, Any]]: ...
