"""Manage stacks and stack definitions."""
from typing import Any
def list_defs() -> list[dict[str, Any]]: ...
    """List stack definitions visible to the current user"""
def get_def(name: str) -> dict[str, Any]: ...
    """Get a stack definition by name or ID"""
def create_def(name: str, description: str = ..., icon_url: str = ..., scope: str = ..., active: bool = ..., groups: list[str] | None = ..., zones: list[str] | None = ..., spaces: list[dict[str, Any]] | None = ...) -> str: ...
    """Create a new stack definition"""
def update_def(name: str, **fields: Any) -> bool: ...
    """Update a stack definition while preserving other fields"""
def delete_def(name: str) -> bool: ...
    """Delete a stack definition"""
def validate_def(spaces: list[dict[str, Any]], name: str = ..., description: str = ..., icon_url: str = ..., scope: str = ..., active: bool = ..., groups: list[str] | None = ..., zones: list[str] | None = ...) -> dict[str, Any]: ...
    """Validate a stack definition without saving"""
def add_component(stack_definition: dict[str, Any], template: str, name: str, description: str = ..., shell: str = ..., **kwargs: Any) -> dict[str, Any]: ...
    """Add a component (template binding) to an existing stack definition. Resolves template name to ID and rejects duplicate component names."""
def remove_component(stack_definition: dict[str, Any], name: str) -> dict[str, Any]: ...
    """Remove a component from a stack definition by name. Also cleans up depends_on and port_forward references in sibling components."""
def create(definition_name: str, prefix: str, stack_name: str | None = ...) -> list[str]: ...
    """Create spaces from a stack definition"""
def delete(stack_name: str) -> bool: ...
    """Delete all spaces in a stack"""
def start(stack_name: str) -> bool: ...
    """Start all spaces in a stack in dependency order"""
def stop(stack_name: str) -> bool: ...
    """Stop all spaces in a stack in reverse dependency order"""
def restart(stack_name: str) -> bool: ...
    """Restart all spaces in a stack"""
def list() -> list[dict[str, Any]]: ...
    """List stacks by grouping spaces by stack name"""
