"""Manage space templates."""
from typing import Any
def list(include_inactive: bool = ...) -> list[dict[str, Any]]: ...
def get(template_id: str) -> dict[str, Any]: ...
def validate(platform: str, job: str = ..., volumes: str = ...) -> dict[str, Any]: ...
def nodes(template_id: str) -> list[dict[str, Any]]: ...
def create(name: str, job: str = ..., description: str = ..., platform: str = ..., volumes: str = ..., active: bool = ..., **kwargs: Any) -> str: ...
def update(template_id: str, name: str | None = ..., job: str | None = ..., description: str | None = ..., platform: str | None = ..., **kwargs: Any) -> bool: ...
def delete(template_id: str) -> bool: ...
def get_icons() -> list[dict[str, Any]]: ...
