"""Manage space templates."""
from typing import Any
def list(include_inactive: bool = ...) -> list[dict[str, Any]]: ...
    """List templates visible to the current user. Defaults to active templates only; pass include_inactive=True to include retired ones."""
def get(template_id: str) -> dict[str, Any]: ...
    """Get template by ID or name"""
def validate(platform: str, job: str = ..., volumes: str = ...) -> dict[str, Any]: ...
    """Validate template job and volume specifications without saving"""
def build_spec(platform: str, spec: dict[str, Any], original_job: str = ..., original_volumes: str = ...) -> dict[str, str]: ...
    """Build native job and volume text from a unified spec (image, environment, ports, storage, memory, cpus). Same conversion as the UI spec wizard. Patch into originals to preserve hand-written content."""
def nodes(template_id: str) -> list[dict[str, Any]]: ...
    """List available placement nodes for a local-container template"""
def create(name: str, job: str = ..., description: str = ..., platform: str = ..., volumes: str = ..., active: bool = ..., **kwargs: Any) -> str: ...
    """Create a new template. health_check_type can be none, agent, tcp, http, program, or custom. ports is a list of {name, port, protocol} objects; jobs is a list of {name, command, schedule, enabled} objects copied into new spaces."""
def update(template_id: str, name: str | None = ..., job: str | None = ..., description: str | None = ..., platform: str | None = ..., **kwargs: Any) -> bool: ...
    """Update template properties, including health_check_type, health_check_auto_restart, ports and jobs"""
def delete(template_id: str) -> bool: ...
    """Delete a template by ID or name"""
def get_icons() -> list[dict[str, Any]]: ...
    """Get list of available icons"""
