"""Manage users."""
from typing import Any
def get_me() -> dict[str, Any]: ...
def get(user_id: str) -> dict[str, Any]: ...
def list(state: str = ..., zone: str = ...) -> list[dict[str, Any]]: ...
def create(username: str, email: str, password: str, active: bool = ..., max_spaces: int = ..., compute_units: int = ..., storage_units: int = ..., max_tunnels: int = ..., ssh_public_key: str = ..., github_username: str = ...) -> str: ...
def update(user_id: str, username: str | None = ..., email: str | None = ..., password: str | None = ..., active: bool | None = ..., max_spaces: int | None = ..., ssh_public_key: str | None = ..., github_username: str | None = ...) -> bool: ...
def set_ssh_public_key(ssh_public_key: str, github_username: str | None = ...) -> bool: ...
def set_ssh_private_key(ssh_private_key: str) -> bool: ...
def delete(user_id: str) -> bool: ...
def get_quota(user_id: str) -> dict[str, Any]: ...
def list_permissions(user_id: str) -> list[dict[str, Any]]: ...
def has_permission(user_id: str, permission_id: int) -> bool: ...
