"""Manage users."""
import builtins
from typing import Any
def get_me() -> dict[str, Any]:
    """Get current user"""
    ...
def get(user_id: str) -> dict[str, Any]:
    """Get user by ID or username"""
    ...
def list(state: str = ..., zone: str = ...) -> builtins.list[dict[str, Any]]:
    """List all users with optional state/zone filter"""
    ...
def create(username: str, email: str, password: str, active: bool = ..., max_spaces: int = ..., compute_units: int = ..., storage_units: int = ..., max_tunnels: int = ..., ssh_public_key: str = ..., github_username: str = ...) -> str:
    """Create a new user"""
    ...
def update(user_id: str, username: str | None = ..., email: str | None = ..., password: str | None = ..., active: bool | None = ..., max_spaces: int | None = ..., ssh_public_key: str | None = ..., github_username: str | None = ...) -> bool:
    """Update user properties"""
    ...
def set_ssh_public_key(ssh_public_key: str, github_username: str | None = ...) -> bool:
    """Set SSH public keys for the current user. Use one public key per line"""
    ...
def set_ssh_private_key(ssh_private_key: str) -> bool:
    """Set the SSH private key for the current user"""
    ...
def delete(user_id: str) -> bool:
    """Delete a user by ID or username"""
    ...
def get_quota(user_id: str) -> dict[str, Any]:
    """Get user quota and usage"""
    ...
def list_permissions(user_id: str) -> builtins.list[dict[str, Any]]:
    """List all permissions for a user"""
    ...
def has_permission(user_id: str, permission_id: int) -> bool:
    """Check if user has a specific permission"""
    ...
