"""Manage template variables."""
from typing import Any
def list() -> list[dict[str, Any]]: ...
def get(var_id: str) -> dict[str, Any]: ...
def create(name: str, value: str, zones: list[str] | None = ..., local: bool = ..., protected: bool = ..., restricted: bool = ...) -> str: ...
def set_value(var_id: str, value: str | None = ...) -> bool: ...
def update(var_id: str, value: str | None = ..., zones: list[str] | None = ..., local: bool | None = ..., protected: bool | None = ..., restricted: bool | None = ...) -> bool: ...
def delete(var_id: str) -> bool: ...
