"""Manage volumes."""
import builtins
from typing import Any
def list() -> builtins.list[dict[str, Any]]:
    """List all volumes"""
    ...
def get(volume_id: str) -> dict[str, Any]:
    """Get volume by ID or name"""
    ...
def nodes(platform: str) -> builtins.list[dict[str, Any]]:
    """List available nodes for a platform"""
    ...
def validate(platform: str, definition: str) -> dict[str, Any]:
    """Validate a volume definition without saving"""
    ...
def create(name: str, definition: str, platform: str = ..., node_id: str = ...) -> str:
    """Create a new volume"""
    ...
def update(volume_id: str, name: str | None = ..., definition: str | None = ..., platform: str | None = ..., node_id: str | None = ...) -> bool:
    """Update volume properties"""
    ...
def delete(volume_id: str) -> bool:
    """Delete a volume by ID or name"""
    ...
def start(volume_id: str) -> bool:
    """Start a stopped volume"""
    ...
def stop(volume_id: str) -> bool:
    """Stop a running volume"""
    ...
def is_running(volume_id: str) -> bool:
    """Check if a volume is currently running"""
    ...
