"""Manage volumes."""
from typing import Any
def list() -> list[dict[str, Any]]: ...
def get(volume_id: str) -> dict[str, Any]: ...
def nodes(platform: str) -> list[dict[str, Any]]: ...
def validate(platform: str, definition: str) -> dict[str, Any]: ...
def create(name: str, definition: str, platform: str = ..., node_id: str = ...) -> str: ...
def update(volume_id: str, name: str | None = ..., definition: str | None = ..., platform: str | None = ..., node_id: str | None = ...) -> bool: ...
def delete(volume_id: str) -> bool: ...
def start(volume_id: str) -> bool: ...
def stop(volume_id: str) -> bool: ...
def is_running(volume_id: str) -> bool: ...
