"""JSON Schema builders for knot.methods Server params and result schemas.

Available wherever knot.methods is available. Import as:
    import knot.methods.schema as s
"""
from typing import Any

def string(*, description: str = ..., default: Any = ..., enum: list[Any] | None = ..., format: str | None = ..., min_length: int | None = ..., max_length: int | None = ..., pattern: str | None = ..., extra: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def integer(*, description: str = ..., default: Any = ..., enum: list[Any] | None = ..., minimum: int | None = ..., maximum: int | None = ..., extra: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def number(*, description: str = ..., default: Any = ..., enum: list[Any] | None = ..., minimum: float | None = ..., maximum: float | None = ..., extra: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def boolean(*, description: str = ..., default: Any = ..., enum: list[Any] | None = ..., extra: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def null(*, description: str = ..., default: Any = ..., enum: list[Any] | None = ..., extra: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def array(items: dict[str, Any], *, description: str = ..., default: Any = ..., enum: list[Any] | None = ..., min_items: int | None = ..., max_items: int | None = ..., extra: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def object(*, description: str = ..., default: Any = ..., enum: list[Any] | None = ..., additional_properties: Any = ..., extra: dict[str, Any] | None = ..., **properties: dict[str, Any]) -> dict[str, Any]: ...
def optional(schema: dict[str, Any], *, default: Any = ...) -> dict[str, Any]: ...
